/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poly.com.ui;

import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import poly.com.DAO.NhanvienDAO;
import poly.com.HELPER.Auth;
import poly.com.HELPER.MsgBox;
import poly.com.HELPER.jdbcHelper;
import poly.com.MODEL.Nhanvien;

/**
 *
 * @author huuho
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form FormLogin2
     */
    boolean flagShowPass = true;
    NhanvienDAO nhanvienDAO = new NhanvienDAO();

    public FormLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        try { 
            lblLogo.setIcon(new ImageIcon(getClass().getResource("/poly/com/icon/icon_logo_login.gif")));
        } catch (Exception e) {
            e.printStackTrace();
        }
        lblLTCT = new javax.swing.JLabel();
        lblManage = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        lblViewPass = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblExit = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblServer = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lblTextIP = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();
        try { 
            lblQR.setIcon(new ImageIcon(getClass().getResource("/poly/com/icon/icon_qrcode.gif")));
        } catch (Exception e) {
            e.printStackTrace();
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(6, 43, 142));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 200));

        lblLTCT.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblLTCT.setForeground(new java.awt.Color(255, 255, 255));
        lblLTCT.setText("LAPTRINHCONGTY");
        jPanel3.add(lblLTCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, 40));

        lblManage.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblManage.setForeground(new java.awt.Color(255, 255, 255));
        lblManage.setText("MANAGE");
        jPanel3.add(lblManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 30, 90, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 360));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsername.setText("Enter username...");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(6, 43, 142)));
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 201, 42));

        lblViewPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/icon/icon_hideeye.png"))); // NOI18N
        lblViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewPassMouseClicked(evt);
            }
        });
        jPanel4.add(lblViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 202, 30, 30));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(6, 43, 142));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 43, 142)));
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setOpaque(true);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 30));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblExit.setForeground(new java.awt.Color(6, 43, 142));
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblExit.setOpaque(true);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblExitMouseExited(evt);
            }
        });
        jPanel4.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPassword.setText("Enter password...");
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(6, 43, 142)));
        txtPassword.setEchoChar((char)0);
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel4.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 201, 42));

        lblLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 38)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(6, 43, 142));
        lblLogin.setText("Login");
        jPanel4.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblServer.setBackground(new java.awt.Color(255, 255, 255));
        lblServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/com/icon/icon_server.gif"))); // NOI18N
        lblServer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblServer.setOpaque(true);
        lblServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblServerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblServerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblServerMouseExited(evt);
            }
        });
        jPanel4.add(lblServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, -1));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        btnExit.setForeground(new java.awt.Color(6, 43, 142));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(6, 43, 142)));
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel4.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, 30));

        lblTextIP.setFont(new java.awt.Font("Segoe UI Light", 0, 15)); // NOI18N
        lblTextIP.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel4.add(lblTextIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 160, 30));

        lblQR.setToolTipText("");
        lblQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQR.setOpaque(true);
        lblQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQRMouseExited(evt);
            }
        });
        jPanel4.add(lblQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 320, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        if (txtUsername.getText().equals("Enter username...")) {
            txtUsername.setText(null);
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if (txtUsername.getText().isEmpty()) {
            txtUsername.setText("Enter username...");
        }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
        if ((byte) evt.getKeyChar() == 10) {
            login();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void lblViewPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewPassMouseClicked
        // TODO add your handling code here:
        if (flagShowPass) {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/poly/com/icon/icon_eye.png")));
            txtPassword.setEchoChar((char) 0);
            this.flagShowPass = false;
        } else {
            lblViewPass.setIcon(new ImageIcon(getClass().getResource("/poly/com/icon/icon_hideeye.png")));
            txtPassword.setEchoChar('*');
            this.flagShowPass = true;
        }
    }//GEN-LAST:event_lblViewPassMouseClicked

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(6, 43, 142));
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(Color.WHITE);
        btnLogin.setForeground(new Color(6, 43, 142));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        if (jdbcHelper.getUrl() == null || jdbcHelper.getUrl().isEmpty()) {
            Runtime.getRuntime().exit(0);
        } else {
            DialogLoading loading = new DialogLoading(this, false);
            loading.setVisible(true);
            new Thread() {
                @Override
                public void run() {
                    new FormMain().setVisible(true);
                    dispose();
                }
            }.start();
        }
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseEntered
        // TODO add your handling code here:
        lblExit.setBackground(new Color(6, 43, 142));
        lblExit.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseExited
        // TODO add your handling code here:
        lblExit.setForeground(new Color(6, 43, 142));
        lblExit.setBackground(null);
    }//GEN-LAST:event_lblExitMouseExited

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        if (String.copyValueOf(txtPassword.getPassword()).equals("Enter password...")) {
            if (this.flagShowPass) {
                txtPassword.setEchoChar('*');
                txtPassword.setText(null);
                return;
            }
            txtPassword.setText(null);
        }
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        if (String.copyValueOf(txtPassword.getPassword()).isEmpty() || String.copyValueOf(txtPassword.getPassword()).equals("Enter password...")) {
            txtPassword.setEchoChar((char) 0);
            txtPassword.setText("Enter password...");
        }
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        if ((byte) evt.getKeyChar() == 10) {
            login();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new Color(6, 43, 142));
        btnExit.setForeground(Color.WHITE);
        btnExit.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.WHITE);
        btnExit.setForeground(new Color(6, 43, 142));
        btnExit.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Runtime.getRuntime().exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void lblServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServerMouseClicked
        // TODO add your handling code here:
        String url = MsgBox.prompt(null, "Nhập IP máy chủ");
        if (url == null) {
            jdbcHelper.setUrl(null);
        } else {
            url = url.trim();
            if (!url.matches("[0-9]+(\\.[0-9]+)*|localhost")) {
                MsgBox.alert(null, "IP Server Không Hợp Lệ");
                return;
            }
            lblTextIP.setText(url);
            jdbcHelper.setUrl(url.trim());
        }
    }//GEN-LAST:event_lblServerMouseClicked

    private void lblServerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServerMouseExited
        // TODO add your handling code here:
        lblServer.setBackground(Color.WHITE);
        lblServer.setForeground(new Color(6, 43, 142));
        lblServer.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10));
    }//GEN-LAST:event_lblServerMouseExited

    private void lblServerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblServerMouseEntered
        // TODO add your handling code here:
        lblServer.setBackground(new Color(6, 43, 142));
        lblServer.setForeground(Color.WHITE);
        lblServer.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10));
    }//GEN-LAST:event_lblServerMouseEntered

    private void lblQRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRMouseEntered
        // TODO add your handling code here:
        lblQR.setBackground(new Color(6, 43, 142));
        lblQR.setForeground(Color.WHITE);
        lblQR.setFont(new java.awt.Font("Segoe UI Emoji", 1, 10));
    }//GEN-LAST:event_lblQRMouseEntered

    private void lblQRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRMouseExited
        // TODO add your handling code here:
        lblQR.setBackground(Color.WHITE);
        lblQR.setForeground(new Color(6, 43, 142));
        lblQR.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10));
    }//GEN-LAST:event_lblQRMouseExited

    private void lblQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRMouseClicked
        // TODO add your handling code here:
        DialogLoading loading = new DialogLoading(this, false);
        loading.setVisible(true);
        ScannerQR qR = new ScannerQR(this, true);
        qR.url = null;
        qR.nv = null;
        Thread thread = new Thread() {
            @Override
            public void run() {
                try {
                    Thread.sleep(2000);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                qR.setVisible(true);
                Auth.user = qR.nv;
                if (Auth.user != null) {
                    System.out.println("a");
                    dispose();
                    new FormMain().setVisible(true);
                }
                if (qR.url != null) {
                    try {
                        System.out.println("b");
                        URL u = new URL(qR.url);
                        Runtime.getRuntime().exec("cmd /c start " + u.toString());
                    } catch (Exception ex) {
                        MsgBox.alert(null, "QR Không Hợp Lệ");
                    }
                }
                loading.dispose();
            }
        };
        thread.setDaemon(true);
        thread.start();
    }//GEN-LAST:event_lblQRMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblLTCT;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblManage;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblTextIP;
    private javax.swing.JLabel lblViewPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
     public boolean validate_form() {
        if (txtUsername.getText().isEmpty() || txtUsername.getText().equals("Enter username...")) {
            txtUsername.requestFocus();
            MsgBox.alert(this, "Không được để trống Username");
            return false;
        }
        if (String.copyValueOf(txtPassword.getPassword()).trim().isEmpty() || String.copyValueOf(txtPassword.getPassword()).equals("Enter password...")) {
            txtPassword.requestFocus();
            MsgBox.alert(this, "Không được để trống Password");
            return false;
        }
        return true;
    }

    public void login() {
        try {
            if (validate_form()) {
                Nhanvien nv = nhanvienDAO.selectById(txtUsername.getText().trim());
                if (nv == null) {
                    MsgBox.alert(this, "Tài khoản không tồn tại");
                } else if (!nv.getMatKhau().equals(String.copyValueOf(txtPassword.getPassword()))) {
                    MsgBox.alert(this, "Sai mật khẩu vui lòng nhập lại");
                } else {
                    Auth.user = nv;
                    DialogLoading loading = new DialogLoading(this, false);
                    loading.setVisible(true);
                    new Thread() {
                        @Override
                        public void run() {
                            new FormMain().setVisible(true);
                            dispose();
                        }
                    }.start();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
